version: "3"

services:
  frontend:
    build: ./frontend
    container_name: "react-ui"
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    build: ./backend
    container_name: node-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - mern-network

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
volumes:
  dbdata6:
